steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 6000s
  args: [ 'build', '-t', 'europe-docker.pkg.dev/filipegracio-ai-learning/haystack-docker-repo/haystack-image:tag1', '.' ]
images:
- 'europe-docker.pkg.dev/filipegracio-ai-learning/haystack-docker-repo/haystack-image:tag1'
