components:
- name: FAISSDocumentStore
  params:
    similarity: cosine
  type: FAISSDocumentStore
- name: Retriever
  params:
    document_store: FAISSDocumentStore
    embedding_model: sentence-transformers/multi-qa-mpnet-base-dot-v1
    model_format: sentence_transformers
  type: EmbeddingRetriever
- name: Reader
  params:
    model_name_or_path: deepset/roberta-base-squad2
  type: FARMReader
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reader
version: 1.11.0rc0
